version: "3"

services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/app
    env_file:
      - .env

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306