name: Deployment production

on:
  push:
    branches: [ master ]

jobs:
  deploy_project:
    name: Build and deploy project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: NPM install
        run: npm install
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just_a_placeholder_to_avoid_errors'
      - name: Adding know hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Create .env
        run: cp .env.example .env
      - name: Set DISCORD_TOKEN env variable
        run: sed -i 's/DISCORD_TOKEN=123456/DISCORD_TOKEN=${{ secrets.PRODUCTION_DISCORD_TOKEN }}/g' .env
      - name: Set GUILD_ID env variable
        run: sed -i 's/GUILD_ID=123456/GUILD_ID=${{ secrets.PRODUCTION_GUILD_ID }}/g' .env
      - name: Set CLIENT_ID env variable
        run: sed -i 's/CLIENT_ID=123456/CLIENT_ID=${{ secrets.PRODUCTION_CLIENT_ID }}/g' .env
      - name: Rsync dry run project with server one
        run: rsync -ravh --dry-run --delete-after --exclude={'.git','.github','node_modules','.gitignore','README.md'} . ${{ secrets.SERVER }}:${{ secrets.PRODUCTION_PROJECT_FOLDER }}
      - name: Rsync project with server one
        run: rsync -ravh --delete-after --exclude={'.git','.github','node_modules','.gitignore','README.md'} . ${{ secrets.SERVER }}:${{ secrets.PRODUCTION_PROJECT_FOLDER }}
      - name: Restart server
        run: ssh ${{ secrets.SERVER }} pm2 restart ${{ secrets.PRODUCTION_PROCESS_NAME }}